# Generated by Django 2.1.5 on 2019-02-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190202_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=models.BooleanField(default=False), null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='national_id_card',
            field=models.ImageField(blank=models.BooleanField(default=False), null=True, upload_to=''),
        ),
    ]
