# Generated by Django 2.1.5 on 2019-02-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=20)),
                ('rooms', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('area', models.IntegerField()),
                ('max_cap', models.IntegerField()),
                ('neighbourhood', models.CharField(max_length=200)),
                ('price_per_night', models.IntegerField()),
                ('available', models.CharField(blank=True, max_length=1000)),
                ('base_image', models.ImageField(upload_to='')),
                ('living_room', models.ImageField(null=True, upload_to='')),
                ('bed_room', models.ImageField(null=True, upload_to='')),
                ('kitchen', models.ImageField(null=True, upload_to='')),
                ('garage', models.ImageField(null=True, upload_to='')),
                ('outside', models.ImageField(null=True, upload_to='')),
                ('description', models.CharField(default='', max_length=10000)),
            ],
        ),
    ]
