# Generated by Django 2.1.5 on 2019-02-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='number_of_reservs',
            field=models.IntegerField(default=0),
        ),
    ]
