# Generated by Django 2.1.5 on 2019-02-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='garage',
        ),
        migrations.AddField(
            model_name='house',
            name='off',
            field=models.IntegerField(default=0),
        ),
    ]
